<p style="text-align:center">
    <a href="https://skills.network/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDA0321ENSkillsNetwork928-2022-01-01" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo"  />
    </a>
</p>

# **Collecting Job Data Using APIs**

## Objectives

After completing this lab, you will be able to:

*   Collect job data from Jobs API
*   Store the collected data into an excel spreadsheet.

#### Instructions

## Dataset Used in this Assignment

The dataset used in this lab comes from the following source: https://www.kaggle.com/promptcloud/jobs-on-naukricom under the under a **Public Domain license**.

> Note: We are using a modified subset of that dataset for the lab, so to follow the lab instructions successfully please use the dataset provided with the lab, rather than the dataset from the original source.

The original dataset is a csv. We have converted the csv to json as per the requirement of the lab.

## Warm-Up Exercise

Before you attempt the actual lab, here is a fully solved warmup exercise that will help you to learn how to access an API.

Using an API, let us find out who currently are on the International Space Station (ISS).<br> The API at [http://api.open-notify.org/astros.json](http://api.open-notify.org/astros.json?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDA0321ENSkillsNetwork21426264-2021-01-01&cm_mmc=Email_Newsletter-_-Developer_Ed%2BTech-_-WW_WW-_-SkillsNetwork-Courses-IBM-DA0321EN-SkillsNetwork-21426264&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ) gives us the information of astronauts currently on ISS in json format.<br>
You can read more about this API at [http://open-notify.org/Open-Notify-API/People-In-Space/](http://open-notify.org/Open-Notify-API/People-In-Space?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDA0321ENSkillsNetwork21426264-2021-01-01&cm_mmc=Email_Newsletter-_-Developer_Ed%2BTech-_-WW_WW-_-SkillsNetwork-Courses-IBM-DA0321EN-SkillsNetwork-21426264&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ)

In [11]:
import requests # you need this module to make an API call
import pandas as pd

In [12]:
api_url = "http://api.open-notify.org/astros.json" # this url gives use the astronaut data

In [13]:
response = requests.get(api_url) # Call the API using the get method and store the
                                # output of the API call in a variable called response.

In [14]:
if response.ok:             # if all is well() no errors, no network timeouts)
    data = response.json()  # store the result in json format in a variable called data
                            # the variable data is of type dictionary.

In [15]:
print(data)   # print the data just to check the output or for debugging

{'people': [{'craft': 'ISS', 'name': 'Oleg Kononenko'}, {'craft': 'ISS', 'name': 'Nikolai Chub'}, {'craft': 'ISS', 'name': 'Tracy Caldwell Dyson'}, {'craft': 'ISS', 'name': 'Matthew Dominick'}, {'craft': 'ISS', 'name': 'Michael Barratt'}, {'craft': 'ISS', 'name': 'Jeanette Epps'}, {'craft': 'ISS', 'name': 'Alexander Grebenkin'}, {'craft': 'ISS', 'name': 'Butch Wilmore'}, {'craft': 'ISS', 'name': 'Sunita Williams'}, {'craft': 'Tiangong', 'name': 'Li Guangsu'}, {'craft': 'Tiangong', 'name': 'Li Cong'}, {'craft': 'Tiangong', 'name': 'Ye Guangfu'}], 'number': 12, 'message': 'success'}

Print the number of astronauts currently on ISS.

In [16]:
print(data.get('number'))

12

Print the names of the astronauts currently on ISS.

In [17]:
astronauts = data.get('people')
print("There are {} astronauts on ISS".format(len(astronauts)))
print("And their names are :")
for astronaut in astronauts:
    print(astronaut.get('name'))

There are 12 astronauts on ISS
And their names are :
Oleg Kononenko
Nikolai Chub
Tracy Caldwell Dyson
Matthew Dominick
Michael Barratt
Jeanette Epps
Alexander Grebenkin
Butch Wilmore
Sunita Williams
Li Guangsu
Li Cong
Ye Guangfu

Hope the warmup was helpful. Good luck with your next lab!

## Lab: Collect Jobs Data using Jobs API

### Objective: Determine the number of jobs currently open for various technologies  and for various locations

Collect the number of job postings for the following locations using the API:

* Los Angeles
* New York
* San Francisco
* Washington DC
* Seattle
* Austin
* Detroit

In [8]:
#Import required libraries
import pandas as pd
import json

#### Write a function to get the number of jobs for the Python technology.<br>
> Note: While using the lab you need to pass the **payload** information for the **params** attribute in the form of **key** **value** pairs.
  
  
 ##### The keys in the json are
 * Job Title

 * Job Experience Required

 * Key Skills

 * Role Category

 * Location

 * Functional Area

 * Industry

 * Role

You can also view  the json file contents  from the following <a href = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DA0321EN-SkillsNetwork/labs/module%201/Accessing%20Data%20Using%20APIs/jobs.json">json</a> URL.

In [37]:
job_url= "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DA0321EN-SkillsNetwork/labs/module%201/Accessing%20Data%20Using%20APIs/jobs.json"

response = requests.get(job_url)
data = response.json()

In [38]:
def get_number_of_jobs_T(technology):
    number_of_jobs = 0
    technology = technology.lower().strip()
    for job in data:
        key_skills_str = job.get('Key Skills', '')
        skills_list = [skill.strip().lower() for skill in key_skills_str.split('|')]
        if technology in skills_list:
           number_of_jobs +=1
    return technology,number_of_jobs

Calling the function for Python and checking if it works.

In [39]:
get_number_of_jobs_T("Python")

('python', 1165)

#### Write a function to find number of jobs in US for a location of your choice

In [50]:
def get_number_of_jobs_L(location):
    number_of_jobs = 0
    search_location = location.lower().strip()
    for job in data:
        location_str = job.get('Location', '').lower().strip()
        if search_location ==  location_str:
           number_of_jobs +=1
    return location,number_of_jobs

Call the function for Los Angeles and check if it is working.

In [55]:
#your code goes here
get_number_of_jobs_L("Los Angeles")[0]

'Los Angeles'

### Store the results in an excel file

Call the API for all the given technologies above and write the results in an excel spreadsheet.

If you do not know how create excel file using python, double click here for **hints**.

<!--

from openpyxl import Workbook        # import Workbook class from module openpyxl
wb=Workbook()                        # create a workbook object
ws=wb.active                         # use the active worksheet
ws.append(['Country','Continent'])   # add a row with two columns 'Country' and 'Continent'
ws.append(['Eygpt','Africa'])        # add a row with two columns 'Egypt' and 'Africa'
ws.append(['India','Asia'])          # add another row
ws.append(['France','Europe'])       # add another row
wb.save("countries.xlsx")            # save the workbook into a file called countries.xlsx


-->

Create a python list of all locations for which you need to find the number of jobs postings.

In [52]:
#your code goes here
Locations = ["Los Angeles","New York","San Francisco","Washington DC","Seattle","Austin","Detroit"]

In [ ]:
from openpyxl import Workbook        # import Workbook class from module openpyxl
wb=Workbook()                        # create a workbook object
ws=wb.active                         # use the active worksheet
ws.append(['Country','Continent'])   # add a row with two columns 'Country' and 'Continent'
ws.append(['Eygpt','Africa'])        # add a row with two columns 'Egypt' and 'Africa'
ws.append(['India','Asia'])          # add another row
ws.append(['France','Europe'])       # add another row
wb.save("countries.xlsx")            # save the workbook into a file called countries.xlsx

Import libraries required to create excel spreadsheet

In [53]:
# your code goes here
from openpyxl import Workbook

Create a workbook and select the active worksheet

In [54]:
# your code goes here
wb=Workbook()
ws=wb.active

Find the number of jobs postings for each of the location in the above list.
Write the Location name and the number of jobs postings into the excel spreadsheet.

In [56]:
#your code goes here
ws.append(['Location','Number of Jobs'])
for location in Locations:
    ws.append([get_number_of_jobs_L(location)[0],get_number_of_jobs_L(location)[1]])

Save into an excel spreadsheet named 'job-postings.xlsx'.

In [58]:
#your code goes here
wb.save("job-postings.xlsx")

In [60]:
pd.read_excel("/content/job-postings.xlsx")

        Location  Number of Jobs
0    Los Angeles             640
1       New York            3226
2  San Francisco             435
3  Washington DC            5316
4        Seattle            3375
5         Austin             434
6        Detroit            3945

#### In the similar way, you can try for below given technologies and results  can be stored in an excel sheet.

Collect the number of job postings for the following languages using the API:

*   C
*   C#
*   C++
*   Java
*   JavaScript
*   Python
*   Scala
*   Oracle
*   SQL Server
*   MySQL Server
*   PostgreSQL
*   MongoDB

In [66]:
# your code goes here
lang_list = ["C","C#","C++","Java","JavaScript","Python","Scala","Oracle","SQL Server","MySQL Server","PostgreSQL","MongoDB"]
wb_lang= Workbook()
ws_lang =wb_lang.active
ws_lang.append(['Language', 'Number of Jobs'])
for lang in lang_list:
    ws_lang.append([get_number_of_jobs_T(lang)[0],get_number_of_jobs_T(lang)[1]])


wb_lang.save("lang_job-postings.xlsx")

In [67]:
pd.read_excel("/content/lang_job-postings.xlsx")

        Language  Number of Jobs
0              c             817
1             c#             487
2            c++             496
3           java            1209
4     javascript            2241
5         python            1165
6          scala              89
7         oracle             614
8     sql server             310
9   mysql server               0
10    postgresql              86
11       mongodb             208

Copyright © 2022 IBM Corporation. All rights reserved.